# Site/SEO settings
email: okay@samesies.io
baseurl: ""
permalink: /:year/:month/:day/:title/
google_analytics: 

name: Mario Canalella
title: My Trading Journal
description: >
  This page serves as a platform for me to document my personal journey in the financial markets, as well as to provide valuable resources and information for fellow traders and enthusiasts.
url: https://mc-mytradingjournal.netlify.app/
twitter_username: thomasvaeth
default_img: /assets/images/seo.jpg
social:
  - name: linkedin
    url: https://www.linkedin.com/in/mario-canalella/
  - name: github
    url: https://github.com/marcanalella
  - name: telegram
    url: https://t.me/mariocanalella

# Contact settings
contact_img: /assets/images/contact-placeholder.gif
formcarry: https://formcarry.com/s/HkIo0nMb7

# Disqus settings
disqus: test-apkdzgmqhj

# MailChimp settings
mailchimp_action: https://samesies.us17.list-manage.com/subscribe/post-json?u=66ddf555dab480e6a8606430b&amp;id=89b3ee034f
mailchimp_input: b_66ddf555dab480e6a8606430b_89b3ee034f

# Author settings
author:
  - name: Mario Canalella
    bio: Software Engineer | Finance Enthusiast
    url: https://mariocanalella.netlify.app/

# Pagination settings
pagination:
  enabled: true
  debug: false
  per_page: 12
  permalink: '/page/:num/'
  title: ':title'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
autopages:
  enabled: true
  categories:
    enabled: false
  collections:
    enabled: false
  tags:
    layouts: 
      - 'tag.html'
    title: 'The Barber Theme'
    permalink: '/tag/:tag'
    slugify:
      mode: raw
      cased: true

# Build settings
markdown: kramdown
plugins:
  - jekyll-paginate-v2
  - jekyll-sitemap
compress_html:
  clippings: all
  comments: all
  startings: [html, head, body]
exclude:
  - node_modules
  - .DS_Store
  - barber.jpg
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - package.json
  - README.md
  - vendor
